env:
  global:
    - LC_CTYPE=en_US.UTF-8
os: osx
language: generic
matrix:
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - os: osx
  include:
    - osx_image: xcode8
      env:
        - JOB=SWIFT_PM
      script:
        - swift build --verbose
        - swift test
    - osx_image: xcode8.1
      env:
        - JOB=SWIFT_PM
      script:
        - swift build --verbose
        - swift test
    - osx_image: xcode8.2
      env:
        - JOB=SWIFT_PM
      script:
        - swift build --verbose
        - swift test
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - xcodebuild ${XCODE_ACTION}
      -project PrettyColors.xcodeproj
      -scheme PrettyColors 
      -sdk ${XCODE_SDK}
      -destination "${XCODE_DESTINATION}"
      CODE_SIGNING_REQUIRED=NO
      CODE_SIGN_IDENTITY=
notifications:
  email: false
